name:                icfp2019
version:             0.1.0.0
github:              "bokesan/icfpc2019"
license:             BSD3
author:              "Christoph Breitkopf"
maintainer:          "chbreitkopf@gmail.com"
copyright:           "2019 Rotten Lambdas"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bokesan/icfpc2019#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- random
- containers

library:
  source-dirs: src

executables:
  icfp2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -rtsopts
    dependencies:
    - icfp2019

tests:
  icfp2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -rtsopts
    dependencies:
    - icfp2019
